version: 2

# Sphinx configuration file location
sphinx:
  configuration: docs/source/conf.py  # Path to your Sphinx conf.py file

# Python environment setup
python:
  interpreter: python3.9  # Specify the Python version
  install:
    - requirements: docs/requirements.txt  # Install dependencies from this file

# Build environment settings
build:
  os: ubuntu-22.04  # Default Ubuntu version
