version: 2

# Sphinx configuration file location
sphinx:
  configuration: source/conf.py

# Python environment setup
python:
  version: "3.10"
  install:
    - requirements: requirements.txt

# Build environment settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - sphinx-build -b html source _build/html
