# .readthedocs.yaml  ─── make sub-modules auto-refresh
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

  # ── NEW: ask RTD to fetch the tip of the tracked branch
  jobs:
    post_checkout:          # runs immediately after git clone
      - git submodule update --init --recursive --remote

submodules:
  include: all              # clone every sub-module
  recursive: true           # and any nested ones

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats: [pdf]

python:
  install:
    - requirements: docs/requirements.txt
